---
- name:                Create container
  become:           yes
  docker_container:
    name:         test
    image:        vulnerables/web-dvwa
    volumes:      /data
  register: docker_inspect

- debug: msg="{{ dcoker_inspect }}"

# TODO : listen syscalls denied to conatiner capabilites (when: dcoker_inspect.Args
# ==privileged)
# TODO: Get binaries installed container (from Docker image)
